SoundConfig={
    [1]={
      id = 1,
      soundName = "������Ч���׶λ��ý���",
      sound = "coin",
      soundPath = "Common/Audio/sound/coin.unity3d",
      soundVol = 1,
  },
    [2]={
      id = 2,
      soundName = "��������1",
      sound = "BG0",
      soundPath = "Common/Audio/BG0.unity3d",
      soundVol = 1,
  },
    [3]={
      id = 3,
      soundName = "��������2",
      sound = "fish_bg_haidishendian",
      soundPath = "Common/Audio/sound/fish_bg_haidishendian.unity3d",
      soundVol = 1,
  },
    [4]={
      id = 4,
      soundName = "��������3",
      sound = "fish_bg_jihaibingchuan",
      soundPath = "Common/Audio/sound/fish_bg_jihaibingchuan.unity3d",
      soundVol = 1,
  },
    [5]={
      id = 5,
      soundName = "��������4",
      sound = "fish_bg_mogusenlin",
      soundPath = "Common/Audio/sound/fish_bg_mogusenlin.unity3d",
      soundVol = 1,
  },
    [6]={
      id = 6,
      soundName = "��������5",
      sound = "fish_bg_shanhuqiantan",
      soundPath = "Common/Audio/sound/fish_bg_shanhuqiantan.unity3d",
      soundVol = 1,
  },
    [7]={
      id = 7,
      soundName = "��������6",
      sound = "fish_bg_shuijinbaozang",
      soundPath = "Common/Audio/sound/fish_bg_shuijinbaozang.unity3d",
      soundVol = 1,
  },
    [8]={
      id = 8,
      soundName = "��������7",
      sound = "game_music",
      soundPath = "Common/Audio/sound/game_music.unity3d",
      soundVol = 1,
  },
    [9]={
      id = 9,
      soundName = "���㽱��̫���ˣ�������������",
      sound = "fish_big_reward",
      soundPath = "Common/Audio/sound/fish_big_reward.unity3d",
      soundVol = 1,
  },
    [10]={
      id = 10,
      soundName = "�����ڵȴ�����",
      sound = "laser_fire",
      soundPath = "Common/Audio/sound/laser_fire.unity3d",
      soundVol = 1,
  },
    [11]={
      id = 11,
      soundName = "�����ڷ���",
      sound = "laser_hit",
      soundPath = "Common/Audio/sound/laser_hit.unity3d",
      soundVol = 1,
  },
    [12]={
      id = 12,
      soundName = "С��Ϸ��ը",
      sound = "minigamebomb",
      soundPath = "Common/Audio/sound/minigamebomb.unity3d",
      soundVol = 1,
  },
    [13]={
      id = 13,
      soundName = "С��Ϸ����",
      sound = "minigameenter",
      soundPath = "Common/Audio/sound/minigameenter.unity3d",
      soundVol = 1,
  },
    [14]={
      id = 14,
      soundName = "С��Ϸ��ʼgo",
      sound = "minigamego",
      soundPath = "Common/Audio/sound/minigamego.unity3d",
      soundVol = 1,
  },
    [15]={
      id = 15,
      soundName = "С��Ϸ׼��ready",
      sound = "minigameready",
      soundPath = "Common/Audio/sound/minigameready.unity3d",
      soundVol = 1,
  },
    [16]={
      id = 16,
      soundName = "С��Ϸ�������ս���",
      sound = "minigamereward",
      soundPath = "Common/Audio/sound/minigamereward.unity3d",
      soundVol = 1,
  },
    [17]={
      id = 17,
      soundName = "С��Ϸ����",
      sound = "minigamescore",
      soundPath = "Common/Audio/sound/minigamescore.unity3d",
      soundVol = 1,
  },
    [18]={
      id = 18,
      soundName = "С��Ϸ������һ��ʼ",
      sound = "minigamestart",
      soundPath = "Common/Audio/sound/minigamestart.unity3d",
      soundVol = 1,
  },
    [19]={
      id = 19,
      soundName = "��������9",
      sound = "Monster_bg_mogusenlin",
      soundPath = "Common/Audio/sound/Monster_bg_mogusenlin.unity3d",
      soundVol = 1,
  },
    [20]={
      id = 20,
      soundName = "����������1",
      sound = "poseidon_coming",
      soundPath = "Common/Audio/sound/poseidon_coming.unity3d",
      soundVol = 1,
  },
    [21]={
      id = 21,
      soundName = "����������2",
      sound = "poseidon_die",
      soundPath = "Common/Audio/sound/poseidon_die.unity3d",
      soundVol = 1,
  },
    [22]={
      id = 22,
      soundName = "������С��Ϸ����",
      sound = "poseidon_game_show",
      soundPath = "Common/Audio/sound/poseidon_game_show.unity3d",
      soundVol = 1,
  },
    [23]={
      id = 23,
      soundName = "������Ϸ���ս���",
      sound = "score_ball_break",
      soundPath = "Common/Audio/sound/score_ball_break.unity3d",
      soundVol = 1,
  },
    [24]={
      id = 24,
      soundName = "������Ϸÿ��ת��ֹͣ",
      sound = "scorechoose",
      soundPath = "Common/Audio/sound/scorechoose.unity3d",
      soundVol = 1,
  },
    [25]={
      id = 25,
      soundName = "�������౻����",
      sound = "shock",
      soundPath = "Common/Audio/sound/shock.unity3d",
      soundVol = 1,
  },
    [26]={
      id = 26,
      soundName = "С��Ϸը����ը",
      sound = "shoot",
      soundPath = "Common/Audio/sound/shoot.unity3d",
      soundVol = 1,
  },
    [27]={
      id = 27,
      soundName = "������Ϸ��ʼת��",
      sound = "switchscreen-huge",
      soundPath = "Common/Audio/sound/switchscreen-huge.unity3d",
      soundVol = 1,
  },
    [28]={
      id = 28,
      soundName = "����ꪱ�����1",
      sound = "tridentcannon",
      soundPath = "Common/Audio/sound/tridentcannon.unity3d",
      soundVol = 1,
  },
    [29]={
      id = 29,
      soundName = "����������ǽ�ڷ���",
      sound = "tridentcollide",
      soundPath = "Common/Audio/sound/tridentcollide.unity3d",
      soundVol = 1,
  },
    [30]={
      id = 30,
      soundName = "����ꪱ�����2",
      sound = "tridentdisappear",
      soundPath = "Common/Audio/sound/tridentdisappear.unity3d",
      soundVol = 1,
  },
    [31]={
      id = 31,
      soundName = "�񽣻���",
      sound = "tridentgetting",
      soundPath = "Common/Audio/sound/tridentgetting.unity3d",
      soundVol = 1,
  },
    [32]={
      id = 32,
      soundName = "�񽣷���",
      sound = "tridentlaunch",
      soundPath = "Common/Audio/sound/tridentlaunch.unity3d",
      soundVol = 1,
  },
    [33]={
      id = 33,
      soundName = "���񿪽�",
      sound = "fish_chaishen",
      soundPath = "Common/Audio/sound/fish_chaishen.unity3d",
      soundVol = 1,
  },
    [34]={
      id = 34,
      soundName = "����������������",
      sound = "fish_coin",
      soundPath = "Common/Audio/sound/fish_coin.unity3d",
      soundVol = 1,
  },
    [35]={
      id = 35,
      soundName = "�������������Ҷ�",
      sound = "fish_few_coins_collect",
      soundPath = "Common/Audio/sound/fish_few_coins_collect.unity3d",
      soundVol = 1,
  },
    [36]={
      id = 36,
      soundName = "������Ч",
      sound = "fish_fire",
      soundPath = "Common/Audio/sound/fish_fire.unity3d",
      soundVol = 1,
  },
    [37]={
      id = 37,
      soundName = "�ӵ�������",
      sound = "fish_items",
      soundPath = "Common/Audio/sound/fish_items.unity3d",
      soundVol = 1,
  },
    [38]={
      id = 38,
      soundName = "����С��Ϸÿ�ε����ĵ���������Ч",
      sound = "fish_large_coins_collect",
      soundPath = "Common/Audio/sound/fish_large_coins_collect.unity3d",
      soundVol = 1,
  },
    [39]={
      id = 39,
      soundName = "����С��Ϸ��bgm",
      sound = "fish_minigame",
      soundPath = "Common/Audio/sound/fish_minigame.unity3d",
      soundVol = 1,
  },
    [40]={
      id = 40,
      soundName = "�ս��ң�����Ʈ����̨��",
      sound = "fish_pearl",
      soundPath = "Common/Audio/sound/fish_pearl.unity3d",
      soundVol = 1,
  },
    [41]={
      id = 41,
      soundName = "���㽱����ɫת��",
      sound = "fish_roulette",
      soundPath = "Common/Audio/sound/fish_roulette.unity3d",
      soundVol = 1,
  },
    [42]={
      id = 42,
      soundName = "ը������������",
      sound = "fish_zhadanhaima",
      soundPath = "Common/Audio/sound/fish_zhadanhaima.unity3d",
      soundVol = 1,
  },
    [43]={
      id = 43,
      soundName = "������Ч",
      sound = "fish_suoding",
      soundPath = "Common/Audio/sound/fish_suoding.unity3d",
      soundVol = 1,
  },
    [44]={
      id = 44,
      soundName = "�㳱��Ч",
      sound = "fish_yuchao",
      soundPath = "Common/Audio/sound/fish_yuchao.unity3d",
      soundVol = 1,
  },
    [45]={
      id = 45,
      soundName = "�ڶ���з����",
      sound = "fish_die_heidongpangxie",
      soundPath = "Common/Audio/sound/fish_die_heidongpangxie.unity3d",
      soundVol = 1,
  },
    [46]={
      id = 46,
      soundName = "�ڶ���з������ȥ",
      sound = "blackholedisappear",
      soundPath = "Common/Audio/sound/blackholedisappear.unity3d",
      soundVol = 1,
  },
    [47]={
      id = 47,
      soundName = "�ڶ���з�ڶ�ѭ��",
      sound = "blackholeappear",
      soundPath = "Common/Audio/sound/blackholeappear.unity3d",
      soundVol = 1,
  },
    [48]={
      id = 48,
      soundName = "��������Ԥ��",
      sound = "blackholecannon",
      soundPath = "Common/Audio/sound/blackholecannon.unity3d",
      soundVol = 1,
  },
    [49]={
      id = 49,
      soundName = "����",
      sound = "fish_die_hujing",
      soundPath = "Common/Audio/sound/fish_die_hujing.unity3d",
      soundVol = 1,
  },
    [50]={
      id = 50,
      soundName = "������",
      sound = "fish_die_huofenghuang",
      soundPath = "Common/Audio/sound/fish_die_huofenghuang.unity3d",
      soundVol = 1,
  },
    [51]={
      id = 51,
      soundName = "������",
      sound = "fish_die_huojiandabaisha",
      soundPath = "Common/Audio/sound/fish_die_huojiandabaisha.unity3d",
      soundVol = 1,
  },
    [52]={
      id = 52,
      soundName = "������",
      sound = "fish_die_jianyu",
      soundPath = "Common/Audio/sound/fish_die_jianyu.unity3d",
      soundVol = 1,
  },
    [53]={
      id = 53,
      soundName = "����",
      sound = "fish_die_jingui",
      soundPath = "Common/Audio/sound/fish_die_jingui.unity3d",
      soundVol = 1,
  },
    [54]={
      id = 54,
      soundName = "�ƽ���ͷ��",
      sound = "fish_die_jinjiachuitousha",
      soundPath = "Common/Audio/sound/fish_die_jinjiachuitousha.unity3d",
      soundVol = 1,
  },
    [55]={
      id = 55,
      soundName = "�ƽ�������1",
      sound = "fish_die_jinkuijiayu",
      soundPath = "Common/Audio/sound/fish_die_jinkuijiayu.unity3d",
      soundVol = 1,
  },
    [56]={
      id = 56,
      soundName = "������",
      sound = "fish_die_jinlongyu",
      soundPath = "Common/Audio/sound/fish_die_jinlongyu.unity3d",
      soundVol = 1,
  },
    [57]={
      id = 57,
      soundName = "��е��з",
      sound = "fish_die_jixiepangxie",
      soundPath = "Common/Audio/sound/fish_die_jixiepangxie.unity3d",
      soundVol = 1,
  },
    [58]={
      id = 58,
      soundName = "��ͷ��",
      sound = "fish_die_kuijialangtousha",
      soundPath = "Common/Audio/sound/fish_die_kuijialangtousha.unity3d",
      soundVol = 1,
  },
    [59]={
      id = 59,
      soundName = "�ƽ�������2",
      sound = "fish_die_kuijiayu_dengwohuiqushengjizhuangbei",
      soundPath = "Common/Audio/sound/fish_die_kuijiayu_dengwohuiqushengjizhuangbei.unity3d",
      soundVol = 1,
  },
    [60]={
      id = 60,
      soundName = "���̽�ţ",
      sound = "fish_die_lunpanjinniu",
      soundPath = "Common/Audio/sound/fish_die_lunpanjinniu.unity3d",
      soundVol = 1,
  },
    [61]={
      id = 61,
      soundName = "���ܻʵۣ��۱��裩",
      sound = "fish_die_qingwahuangdi",
      soundPath = "Common/Audio/sound/fish_die_qingwahuangdi.unity3d",
      soundVol = 1,
  },
    [62]={
      id = 62,
      soundName = "����",
      sound = "fish_die_qiyu",
      soundPath = "Common/Audio/sound/fish_die_qiyu.unity3d",
      soundVol = 1,
  },
    [63]={
      id = 63,
      soundName = "��������",
      sound = "fish_die_shandianhetun",
      soundPath = "Common/Audio/sound/fish_die_shandianhetun.unity3d",
      soundVol = 1,
  },
    [64]={
      id = 64,
      soundName = "����",
      sound = "fish_die_suijifenboss",
      soundPath = "Common/Audio/sound/fish_die_suijifenboss.unity3d",
      soundVol = 1,
  },
    [65]={
      id = 65,
      soundName = "������",
      sound = "fish_die_yinlongyu",
      soundPath = "Common/Audio/sound/fish_die_yinlongyu.unity3d",
      soundVol = 1,
  },
    [66]={
      id = 66,
      soundName = "ը������",
      sound = "fish_die_zhadanhaima",
      soundPath = "Common/Audio/sound/fish_die_zhadanhaima.unity3d",
      soundVol = 1,
  },
    [67]={
      id = 67,
      soundName = "����DJ1",
      sound = "fish_die_zhangyudj",
      soundPath = "Common/Audio/sound/fish_die_zhangyudj.unity3d",
      soundVol = 1,
  },
    [68]={
      id = 68,
      soundName = "����DJ2",
      sound = "fish_die_zhangyudj_wurenjiashinvhaizi",
      soundPath = "Common/Audio/sound/fish_die_zhangyudj_wurenjiashinvhaizi.unity3d",
      soundVol = 1,
  },
    [69]={
      id = 69,
      soundName = "����DJ3",
      sound = "fish_die_zhangyudj_yoyo",
      soundPath = "Common/Audio/sound/fish_die_zhangyudj_yoyo.unity3d",
      soundVol = 1,
  },
    [70]={
      id = 70,
      soundName = "�����ڵ�ͷ����",
      sound = "fish_dantoufashe",
      soundPath = "Common/Audio/sound/fish_dantoufashe.unity3d",
      soundVol = 1,
  },
    [71]={
      id = 71,
      soundName = "����ꪺ�������ײ����",
      sound = "fish_dantoujizhong",
      soundPath = "Common/Audio/sound/fish_dantoujizhong.unity3d",
      soundVol = 1,
  },
    [72]={
      id = 72,
      soundName = "����",
      sound = "fish_die_caishenyu",
      soundPath = "Common/Audio/sound/fish_die_caishenyu.unity3d",
      soundVol = 1,
  },
    [73]={
      id = 73,
      soundName = "��ͷ��",
      sound = "fish_die_chuitousha",
      soundPath = "Common/Audio/sound/fish_die_chuitousha.unity3d",
      soundVol = 1,
  },
    [74]={
      id = 74,
      soundName = "��������",
      sound = "fish_die_gangtiebawang",
      soundPath = "Common/Audio/sound/fish_die_gangtiebawang.unity3d",
      soundVol = 1,
  },
    [75]={
      id = 75,
      soundName = "����������ꪣ�",
      sound = "fish_die_haishen",
      soundPath = "Common/Audio/sound/fish_die_haishen.unity3d",
      soundVol = 1,
  },
    [76]={
      id = 76,
      soundName = "�ƽ�������",
      sound = "fish_die_huangjinshenxianyu",
      soundPath = "Common/Audio/sound/fish_die_huangjinshenxianyu.unity3d",
      soundVol = 1,
  },
    [77]={
      id = 77,
      soundName = "������",
      sound = "fish_die_hudieyu",
      soundPath = "Common/Audio/sound/fish_die_hudieyu.unity3d",
      soundVol = 1,
  },

	 [78]={
      id = 78,
      soundName = "������",
      sound = "Fish_15",
      soundPath = "Common/Audio/Fish_15.unity3d",
      soundVol = 1,
  },

	[79]={
      id = 79,
      soundName = "������",
      sound = "Fish_16",
      soundPath = "Common/Audio/Fish_16.unity3d",
      soundVol = 1,
  },

	[80]={
      id = 79,
      soundName = "������",
      sound = "Fish_16",
      soundPath = "Common/Audio/Fish_16.unity3d",
      soundVol = 1,
  },

	[81]={
      id = 81,
      soundName = "������",
      sound = "Fish_17",
      soundPath = "Common/Audio/Fish_17.unity3d",
      soundVol = 1,
  },

	[82]={
      id = 81,
      soundName = "������",
      sound = "Fish_18",
      soundPath = "Common/Audio/Fish_18.unity3d",
      soundVol = 1,
  },

	[83]={
      id = 83,
      soundName = "������",
      sound = "Fish_19",
      soundPath = "Common/Audio/Fish_19.unity3d",
      soundVol = 1,
  },


	[84]={
      id = 84,
      soundName = "������",
      sound = "Fish_20",
      soundPath = "Common/Audio/Fish_20.unity3d",
      soundVol = 1,
  },

	[85]={
      id = 85,
      soundName = "������",
      sound = "Fish_21",
      soundPath = "Common/Audio/Fish_21.unity3d",
      soundVol = 1,
  },

	[86]={
      id = 86,
      soundName = "������",
      sound = "Fish_22",
      soundPath = "Common/Audio/Fish_22.unity3d",
      soundVol = 1,
  },

	[87]={
      id = 87,
      soundName = "������",
      sound = "Fish_23",
      soundPath = "Common/Audio/Fish_23.unity3d",
      soundVol = 1,
  },

	[88]={
      id = 88,
      soundName = "������",
      sound = "Fish_24",
      soundPath = "Common/Audio/Fish_24.unity3d",
      soundVol = 1,
  },

	[89]={
      id = 89,
      soundName = "������",
      sound = "Fish_25",
      soundPath = "Common/Audio/Fish_25.unity3d",
      soundVol = 1,
  },

	[90]={
      id = 90,
      soundName = "������",
      sound = "Fish_26",
      soundPath = "Common/Audio/Fish_26.unity3d",
      soundVol = 1,
  },

	[91]={
      id = 91,
      soundName = "������",
      sound = "Fish_27",
      soundPath = "Common/Audio/Fish_27.unity3d",
      soundVol = 1,
  },

	[92]={
      id = 92,
      soundName = "������",
      sound = "Fish_28",
      soundPath = "Common/Audio/Fish_28.unity3d",
      soundVol = 1,
  },

	[93]={
      id = 93,
      soundName = "������",
      sound = "Fish_29",
      soundPath = "Common/Audio/Fish_29.unity3d",
      soundVol = 1,
  },

	[94]={
      id = 94,
      soundName = "������",
      sound = "Fish_30",
      soundPath = "Common/Audio/Fish_30.unity3d",
      soundVol = 1,
  },
  [95]={
    id = 95,
    soundName = "BG1",
    sound = "BG1",
    soundPath = "Common/Audio/BG1.unity3d",
    soundVol = 1,
  },
  [96]={
    id = 96,
    soundName = "BG2",
    sound = "BG2",
    soundPath = "Common/Audio/BG2.unity3d",
    soundVol = 1,
  },
  [97]={
    id = 97,
    soundName = "BG3",
    sound = "BG3",
    soundPath = "Common/Audio/BG3.unity3d",
    soundVol = 1,
  },
  [98]={
    id = 98,
    soundName = "effect2311",
    sound = "effect2311",
    soundPath = "Common/Audio/Sound/effect2311.unity3d",
    soundVol = 1,
  },
  [99]={
    id = 99,
    soundName = "effect2312",
    sound = "effect2312",
    soundPath = "Common/Audio/Sound/effect2312.unity3d",
    soundVol = 1,
  },
  [100]={
    id = 100,
    soundName = "effect2313",
    sound = "effect2313",
    soundPath = "Common/Audio/Sound/effect2313.unity3d",
    soundVol = 1,
  },
  [101]={
    id = 101,
    soundName = "effect2314",
    sound = "effect2314",
    soundPath = "Common/Audio/Sound/effect2314.unity3d",
    soundVol = 1,
  },
  [102]={
    id = 102,
    soundName = "effect2315",
    sound = "effect2315",
    soundPath = "Common/Audio/Sound/effect2315.unity3d",
    soundVol = 1,
  },
  [103]={
    id = 103,
    soundName = "effect2316",
    sound = "effect2316",
    soundPath = "Common/Audio/Sound/effect2316.unity3d",
    soundVol = 1,
  },
  [104]={
    id = 104,
    soundName = "effect2317",
    sound = "effect2317",
    soundPath = "Common/Audio/Sound/effect2317.unity3d",
    soundVol = 1,
  },
  [105]={
    id = 105,
    soundName = "effect2318",
    sound = "effect2318",
    soundPath = "Common/Audio/Sound/effect2318.unity3d",
    soundVol = 1,
  },
  [106]={
    id = 106,
    soundName = "effect2319",
    sound = "effect2319",
    soundPath = "Common/Audio/Sound/effect2319.unity3d",
    soundVol = 1,
  },
  [107]={
    id = 107,
    soundName = "effect2320",
    sound = "effect2320",
    soundPath = "Common/Audio/Sound/effect2320.unity3d",
    soundVol = 1,
  },
  [108]={
    id = 108,
    soundName = "fish_huanpao",
    sound = "fish_huanpao",
    soundPath = "Common/Audio/Sound/fish_huanpao.unity3d",
    soundVol = 1,
  },
  [109]={
    id = 109,
    soundName = "fish_win",
    sound = "fish_win",
    soundPath = "Common/Audio/Sound/fish_win.unity3d",
    soundVol = 1,
  },
  [110]={
    id = 110,
    soundName = "fish_kaipao",
    sound = "fish_kaipao",
    soundPath = "Common/Audio/Sound/fish_kaipao.unity3d",
    soundVol = 1,
  },
  [111]={
    id = 111,
    soundName = "fish_kaipao",
    sound = "fish_kaipao",
    soundPath = "Common/Audio/Sound/fish_kaipao.unity3d",
    soundVol = 1,
  },
  [112]={
    id = 112,
    soundName = "fish_tongyong",
    sound = "fish_tongyong",
    soundPath = "Common/Audio/Sound/fish_tongyong.unity3d",
    soundVol = 1,
  },
  [113]={
    id = 113,
    soundName = "fish_anniu",
    sound = "fish_anniu",
    soundPath = "Common/Audio/Sound/fish_anniu.unity3d",
    soundVol = 1,
  },
  [114]={
    id = 114,
    soundName = "fish_guanbi",
    sound = "fish_guanbi",
    soundPath = "Common/Audio/Sound/fish_guanbi.unity3d",
    soundVol = 1,
  },
  [115]={
    id = 115,
    soundName = "fish_bindongyu",
    sound = "fish_bindongyu",
    soundPath = "Common/Audio/Sound/fish_bindongyu.unity3d",
    soundVol = 1,
  },
  [116]={
    id = 116,
    soundName = "fish_shock",
    sound = "fish_shock",
    soundPath = "Common/Audio/Sound/fish_shock.unity3d",
    soundVol = 1,
  },
  [117]={
    id = 117,
    soundName = "fish_shock",
    sound = "fish_shock",
    soundPath = "Common/Audio/Sound/fish_shock.unity3d",
    soundVol = 1,
  },
}


