# Disable ModemManager integration - this is a pentesting computer, not a phone
[main]
plugins=ifupdown,keyfile
no-auto-default=*

[keyfile]
unmanaged-devices=interface-name:wwan*;interface-name:cdc-wdm*
